backend:
  name: git-gateway
  branch: master
media_folder: "/src/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogposts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "{{media_folder}}/blogposts"
    public_folder: "{{public_folder}}/blogposts"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Intro", name: "blogIntro", widget: "string" }
      - {
          label: "Image",
          name: "blogImage",
          widget: "image",
          allow_multiple: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
